function affiche(){
  skill_tableau = document.forms['skill'].nomskill.value;

  if ( level > pet_level[skill_tableau] )
  {
    lvl = pet_level[skill_tableau];
  }
  else
  {
    lvl = level;
  }

  //lvl pet + sp requis
  document.getElementById('petlvl').innerHTML="<span style=\"color:#96f5ff\">"+pet[skill_tableau][0][lvl]+"</span>";
  document.getElementById('spirit').innerHTML="<span style=\"color:#96f5ff\">"+pet[skill_tableau][1][lvl]+"</span>";

  //info skill
  switch (skill_tableau) {
    case "6871" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Bash&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>8　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Launch a fierce strike at the enemy, dealing </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of Pet's base physical damage.</span>";
    break;
    case "7471" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Flesh Ream&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")&nbsp;&nbsp;<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Bite an enemy, inflicting base damage plus </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of Pet's base damage over 9 seconds.</span>";
    break;
    case "7481" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Fireball&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")&nbsp;&nbsp;<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>8 </span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Hurl a fireball at the enemy, inflicting Fire <br />damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of Pet's base physical damage.</span>";
    break;
    case "7491" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Icicle&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /> <br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>8　</span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Throw an icicle at the enemy, inflicting Water<br />damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of Pet's base physical damage.</span>";
    break;
    case "7501" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Toxic Mist&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>8　</span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Cast a fog of toxin on the enemy, inflicting<br />Wood damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of Pet's base physical damage.</span>";
    break;
    case "7511" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Thunderbolt&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'></span><br /><span style='color:#ffcb4a'>Cooldown </span><span style='color:#ffffff'>8　</span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Launch a thunderbolt at the enemy, inflicting Metal<br />damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of Pet's base physical damage.</span>";
    break;
    case "7521" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Sandblow&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br />&nbsp;&nbsp;<br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>8　</span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Cast a blow of sand to the enemy, inflicting Earth<br />damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of Pet's base physical damage.</span>";
    break;
    case "7531" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Roar&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")&nbsp;&nbsp;<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Roar to attract enemy's attacks.</span>";
    break;
    case "7541" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Howl&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")&nbsp;&nbsp;<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Scare the enemy with a howl, decreasing<br />enemy's Magic Defense by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for 15 secs.</span>";
    break;
    case "7551" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Pierce&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br />&nbsp;&nbsp;<br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Attack enemy and decrease enemy's Physical<br />Defense by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for 15 secs.</span>";
    break;
    case "7561" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Threaten&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /><br />&nbsp;&nbsp;</span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffffff'>Threaten enemy to decrease enemy's Physical<br />Attack by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for 15 secs.</span>";
    break;
    case "7571" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Shriek&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /><br />&nbsp;&nbsp;</span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffffff'>Shriek at an enemy to have a </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance to interrupt channelling.</span>";
    break;
    case "7581" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Slow&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")&nbsp;&nbsp;<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffffff'>Decrease enemy speed by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for 6 secs.</span>";
    break;
    case "7591" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Tough&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br />&nbsp;&nbsp;<br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>60　</span><span style='color:#ffcb4a'>sec <br /></span><span style='color:#ffffff'>Reduce damage taken by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for 15 secs.</span>";
    break;
    case "7601" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Boost&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>3　</span><br /><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffffff'>Recover </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of Maximum HP.</span>";
    break;
    case "7611" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Pounce&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")&nbsp;&nbsp;<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>2　</span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>60　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffffff'>Have a 80% chance to stun enemy for 3 secs. <br />Increase attack rate by</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for 15 secs if enemy is stunned.</span>";
    break;
    case "7951" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Bloodthirst&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /> <br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>3　</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Drain enemy life equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of<br />Pet's Maximum HP, restoring Pet's life.</span>";
    break;
    case "7961" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Consume&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /> <br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>3　</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Drain Mana from the enemy equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of<br />Pet's Maximum HP, restoring Pet's life.</span>";
    break;
    case "7971" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Bloodhunger<br /> <br /> </span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffcb4a'>Requisite Skill　</span><span style='color:#ffffff'>Level 3 Bloodthirst<br /> </span><span style='color:#ffffff'>Absorb enemy's life equal to half of <br />Pet's missing HP, restoring Pet's life.</span>";
    break;
    case "7981" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Devour&nbsp;&nbsp;<br /><br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffcb4a'>Requisite Skill　</span><span style='color:#ffffff'>Level 3 Consume<br /> </span><span style='color:#ffffff'>Absorb enemy's Mana equal to half<br /> of Pet's missing HP, restoring Pet's life.</span>";
    break;
    case "7991" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Sacrifice<br />&nbsp;&nbsp;<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffffff'>Lose 75% of current HP to inflict 400% of Pet's base physical damage to an enemy.</span>";
    break;
    case "8001" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Penetrate&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br />&nbsp;&nbsp;<br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffffff'>A fierce attack which inflicts </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> damage,<br /> neglecting target's defense.</span>";
    break;
    case "8011" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Reflect&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br />&nbsp;&nbsp;<br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>3　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffffff'>Reflect </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of melee damage taken for 1 hour.</span>";
    break;
    case "8021" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Claw&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")&nbsp;&nbsp;<br /><br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>3　</span><span style='color:#ffcb4a'>seconds <br /></span><span style='color:#ffffff'>Increase attack power by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for 1 hour.</span>";
    break;
    case "8031" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Protect&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br />&nbsp;&nbsp;<br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>3　</span><span style='color:#ffcb4a'>sec<br /></span><span style='color:#ffffff'>Increase Pet's Magic Defense by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for 1 hour.</span>";
    break;
    case "8041" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Strong&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /> <br /></span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>3　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffffff'>Increase Pet's Physical Defense by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for 1 hour, but reduces Evasion to 0.</span>";
    break;
    case "8051" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Blessing of the Pack&nbsp;&nbsp;(Level "+pet[skill_tableau][2][lvl]+")<br /> <br /> </span><span style='color:#ffcb4a'>Maximum Skill Level　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'><br /> </span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>3　</span><span style='color:#ffcb4a'>sec<br /> </span><span style='color:#ffffff'>Increase Pet's Maximum HP by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for 1 hour.</span>";
    break;
    case "20581" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ghost　　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>Instant</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds <br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Damage from players is reduced by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>. </span>";
    break;
    case "20591" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Soul Eating　　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast 　</span><span style='color:#ffffff'>0.1　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>chance to stun target for </span><span style='color:#96f5ff'>2</span><span style='color:#ffffff'> seconds when attacking. </span>";
    break;
    case "20611" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Spirit 　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>You are unselectable by players. Lasts for </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+" </span><span style='color:#ffffff'>seconds.</span>";
    break;
    case "20621" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Bloodthirst　　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>Instant</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance to recover your max HP by </span><span style='color:#96f5ff'>"+pet[skill_tableau][4][lvl]+"%</span><span style='color:#ffffff'>.</span>";
    break;
    case "20771" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Combat Saint<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Damage directly dealt by the player is reduced by 60%,<br />Max HP increased by 30%.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Avatar of War</span>";
    break;
    case "20781" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Phoenix Wings Flying <br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1 </span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>1.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Deals Fire Damge equal to 133% of attack power to ground targets,<br />deals 3 times damage to aerial targets.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Heliacal Phoenix</span>";
    break;
    case "20791" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Gold Armor Deity<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>1.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Deals massive physical damage of 100% attack power in a line enemies within 10 meters,<br />and the effect of received damage reduced 15%, lasts 15 seconds.<br /><br /></span><span style='color:#a6caf0'>Reduced damage effect can stack with Hardness<br /></span><span style='color:#a6caf0'>Special Skill of Celestial Giant</span>";
    break;
    case "20801" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Bone Sickle<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Deals 200% attack power single physical damage to targets,<br />deals extra 150% attack power physical damage to monsters.<br /><br /></span><span style='color:#a6caf0'>Deals large amount of damage to enemy's pet<br /></span><span style='color:#a6caf0'>Special Skill of Imperial Skeleton</span>";
    break;
    case "20811" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ice Stone Armor<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Defense level increased by 20 points.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Supreme Walker</span>";
    break;
    case "20821" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Bee Thorn<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>20　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Deals Wood damage of 100% attack power to targets and reduces their flying speed by 50%,<br />lasts 8 seconds, deals 3 times damage to aerial targets.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Thorn Bee</span>";
    break;
    case "20831" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Reborn In Fire<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>90　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Recovers 70% HP, and defense level increased by 200 within 6 seconds.<br /></span><span style='color:#a6caf0'>Special Skill of Flaming Crystal</span>";
    break;
    case "20841" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Tsunami<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>20　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Inflicts water damage at 650% of basic physical attack.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Fantastical Angelfish</span>";
    break;
    case "20851" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Tsunami<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>20　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Inflicts water damage at 650% of basic physical attack.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Fantastical Angelfish</span>";
    break;
    case "20861" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Night<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>20　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Avoid to be targeted by players, lasts </span><span style='color:#96f5ff'>"+pet[skill_tableau][2][lvl]+"</span><span style='color:#ffffff'>seconds.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Night Prowler</span>";
    break;
    case "20871" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Flying Lace Attack<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Knock Back target by 10 meters, avaliable to players.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Lil' Dolphy</span>";
    break;
    case "20881" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Boo<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has 70% chance to stun target for 2 seconds.<br /><br /></span><span style='color:#a6caf0'>Special Skill of King Cuddlesworth</span>";
    break;
    case "20891" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Loyal Dog<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Make enemy players only can target Valiant Protector within 4 seconds.<br /><br />'Master, run!'<br /><br /></span><span style='color:#a6caf0'>Special Skill of Valiant Protector</span>";
    break;
    case "20901" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Shadow Dash<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Four-leg Drizzy runs faster! Movement speed increased to Drizzy, and Evasion increased by 400%.<br /><br />'Give my body back!' You think that you can hear this shout, never mind, it's just in my head.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Drizzy</span>";
    break;
    case "20911" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Disable Magic<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Reduces target's attack speed, movement speed, and channeling speed by 50%, lasts 8 seconds.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Moon Toad</span>";
    break;
    case "20921" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Weak Toxin<br /><br /></span><span style='color:#ffcb4a'>Range　</span><span style='color:#ffffff'>12 meters<br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Reduces the Physical and Magic Attacks of all enemies within 10 meters by 50%. Lasts 4 seconds. if the target is player, then the effect increased to 200%.<br /><br /></span><span style='color:#a6caf0'>Special Skill of Shademark Scorpion</span>";
    break;
    case "20931" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Spirit Destory<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Increase skill damage to monsters by 30%,<br />Max HP increased by 30%.<br /><br /></span><span style='color:#a6caf0'>The damage increase can stack with Wraithslayer<br /><br /></span><span style='color:#a6caf0'>Special Skill of Empyrean Harpy</span>";
    break;
    case "20941" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Imprison　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance to Freeze the target for </span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'> seconds when attacking.</span>";
    break;
    case "20961" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Cripple　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance to<br />slow target by </span><span style='color:#96f5ff'>70%</span><span style='color:#ffffff'>, lasts </span><span style='color:#96f5ff'>6</span><span style='color:#ffffff'> seconds when attacking.</span>";
    break;
    case "20981" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Quiet　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance to<br />seal target for</span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'>seconds when attacking.</span>";
    break;
    case "21001" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Break Blade　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance to nullify the target's weapon for</span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'>seconds when attacking.</span>";
    break;
    case "21021" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Overload　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a</span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'> chance on attack, extend target's cooldowns by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>, lasts </span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'>seconds.This is less effective on monsters.<br /></span>";
    break;
    case "21041" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Noise　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a</span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'> chance, on attack, to extend the target's cooldowns by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>, lasts</span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'>seconds.This effect is reduced on monsters.<br /></span>";
    break;
    case "21061" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Soulcough　　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance, on attack, to interrupt the target's cast. This effect is reduced on monsters.</span>";
    break;
    case "21081" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Eat Soul　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has </span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'> chance, on attack, to to reduce the target's Chi by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>.</span>";
    break;
    case "21101" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Sharp　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance, on attack, to deal Metal damage equal to attack damage. This effect is lessened for monsters.<br /></span>";
    break;
    case "21121" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Grounding　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance to disable the target's flight for</span><span style='color:#96f5ff'>1</span><span style='color:#ffffff'>seconds.</span>";
    break;
    case "21141" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Corroding　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a </span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'> chance to reduce target's Physical Attack and Magic Attack by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> for </span><span style='color:#96f5ff'>6</span><span style='color:#ffffff'>seconds. Less effective against monsters.<br /></span>";
    break;
    case "21161" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Provoking　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a </span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'> chance to attract all targets surrounding you. Higher level, greater threat.<br /></span>";
    break;
    case "21181" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Craze　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance to increase your attack rate by </span><span style='color:#96f5ff'>25%</span><span style='color:#ffffff'> for </span><span style='color:#96f5ff'>12</span><span style='color:#ffffff'> seconds.</span>";
    break;
    case "21201" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Precision　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Increase Precision by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>.</span>";
    break;
    case "21211" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Wraithslayer　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Increase skill damage by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> when attacking monsters.</span>";
    break;
    case "21221" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Flash　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Has a</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> chance to evade normal damage.</span>";
    break;
    case "21231" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Regeneration　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Every </span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'> seconds, recover </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of your own Max HP over </span><span style='color:#96f5ff'>30</span><span style='color:#ffffff'> seconds.</span>";
    break;
    case "21241" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Unyielding　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Increase defense level by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>.</span>";
    break;
    case "21251" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Morale　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Increase attack level by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>.</span>";
    break;
    case "21261" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ares　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Increase attack and defense level by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>.</span>";
    break;
    case "21271" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Mind　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Increase attack and defense level by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> while reducing damage from players by </span><span style='color:#96f5ff'>55%</span>";
    break;
    case "21281" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Petrifaction　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Immune to immobilize effects.</span>";
    break;
    case "21291" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Self-healing　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>90　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Recover </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of your Max HP.</span>";
    break;
    case "21301" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Flame Fist　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.2&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>1.0&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>1.0　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Inflict fire damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of your base damage.</span>";
    break;
    case "21311" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Justice　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Inflict physical damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of your base damage.</span>";
    break;
    case "21321" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Assassination　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Range　</span><span style='color:#ffffff'>27 meters<br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Inflict physical damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of your base damage.</span>";
    break;
    case "21331" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Assassination　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.2&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>1.0&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>1.0　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Inflict physical damage equal to </span><span style='color:#96f5ff'>100%</span><span style='color:#ffffff'>-</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> of your base damage. The less HP your target has, the greater damage you can deal.<br />Less effective to monsters.</span>";
    break;
    case "21341" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Shocking Sky　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.2&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>1.0&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>1.0　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Inflict physical damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> your base damage. Deal </span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'>X Damage to targets in sky.</span>";
    break;
    case "21351" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Howl　　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>20　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>To targets within </span><span style='color:#96f5ff'>12</span><span style='color:#ffffff'> meters and to deals </span><span style='color:#96f5ff'>100%</span><span style='color:#ffffff'> attack power damage, deals large amount of massive threat.The threat related to skill level and <br />pet's max HP.</span>";
    break;
    case "21361" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Demon Hunting　　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1 </span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Damon Hunting level increased by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> points.</span>";
    break;
    case "21381" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Rule The World<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.2&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>2.5&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Deals Physical Damage equal to</span><span style='color:#96f5ff'>300%</span><span style='color:#ffffff'> of attack power to the target, stuns it for </span><span style='color:#96f5ff'>2</span><span style='color:#ffffff'>seconds, and raises attack power by </span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'>.<br /><br /></span><span style='color:#a6caf0'>Cannot be relearned.</span>";
    break;
    case "21391" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Heavy Load<br /><br /></span><span style='color:#ffcb4a'>Range　</span><span style='color:#ffffff'>15 meters<br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.2&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>1.3&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>To the target and surrounding enemies within </span><span style='color:#96f5ff'>6</span><span style='color:#ffffff'>meters and to deals Physical Damage equal to</span><span style='color:#96f5ff'>100%</span><span style='color:#ffffff'>attack damage. Stuns players for</span><span style='color:#96f5ff'>2</span><span style='color:#ffffff'>seconds.<br /><br /></span><span style='color:#a6caf0'>Cannot be relearned.<br /></span>";
    break;
    case "21401" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ice Stick<br /><br /></span><span style='color:#ffcb4a'>Range　</span><span style='color:#ffffff'>27meters<br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.5&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>1.0&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>1.0　</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffffff'>Deals Water Damage to&nbsp;&nbsp;the target equal to </span><span style='color:#96f5ff'>200%</span><span style='color:#ffffff'>of attack damage. Deals extra Water Damage equal to </span><span style='color:#96f5ff'>150%</span><span style='color:#ffffff'> of attack power.<br /><br /></span><span style='color:#a6caf0'>Damage is increased on enemy pets.<br /></span><span style='color:#a6caf0'>Cannot be relearned.</span>";
    break;
    case "21411" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Fallen Leaf and Flying Flowers<br /><br /></span><span style='color:#ffcb4a'>Range　</span><span style='color:#ffffff'>27meters<br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>1.0&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>1.5&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>1.5&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>To the target and surrounding enemies within </span><span style='color:#96f5ff'>10</span><span style='color:#ffffff'>meters and to deals Wood Damage equal to </span><span style='color:#96f5ff'>200%</span><span style='color:#ffffff'>of attack damage. Deals extra Wood damage equal to </span><span style='color:#96f5ff'>100%</span><span style='color:#ffffff'> of attack power to monsters.<br /><br /></span><span style='color:#a6caf0'>Damage is increased on enemy pets<br /></span><span style='color:#a6caf0'>Cannot be relearned.<br /></span>";
    break;
    case "21421" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Bare-handed Cut<br /><br /></span><span style='color:#ffcb4a'>Range　</span><span style='color:#ffffff'>27meters<br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>1.0&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>1.5&nbsp;&nbsp;</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>To the target and surrounding enemies who within </span><span style='color:#96f5ff'>10</span><span style='color:#ffffff'>meters and to deals Physical Damage equal to </span><span style='color:#96f5ff'>200%</span><span style='color:#ffffff'>off attack damage. Stuns monsters for</span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'>seconds.<br /><br /></span><span style='color:#a6caf0'>Cannot be relearned.</span>";
    break;
    case "21461" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Shadow　　　　　　　　　　　　　Level "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Channel　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cast　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>second<br /></span><span style='color:#ffcb4a'>Cooldown　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>seconds<br /></span><span style='color:#ffffff'>Increased chance to avoid debuffs by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span>";
    break;
  }
}
