function affiche(){
  skill_tableau = document.forms['skill'].nomskill.value;

  if ( level > pet_level[skill_tableau] )
  {
    lvl = pet_level[skill_tableau];
  }
  else
  {
    lvl = level;
  }

  //lvl pet + sp requis
  document.getElementById('petlvl').innerHTML="<span style=\"color:#96f5ff\">"+pet[skill_tableau][0][lvl]+"</span>";
  document.getElementById('spirit').innerHTML="<span style=\"color:#96f5ff\">"+pet[skill_tableau][1][lvl]+"</span>";

  //info skill
  switch (skill_tableau) {
    case "6871" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Яростная атака&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>8</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Мощная атака, наносящая урон в размере </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> от базового физического урона питомца.</span>";
    break;
    case "7471" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Яростный укус&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>15</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Разрывает противника клыками, нанося базовый физический урон и оставляя глубокие раны.<br />Кровотечение наносит еще </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базового физического урона за 9 сек.</span>";
    break;
    case "7481" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Огненный шар&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>8</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Бросает в противника пылающий шар, наносящий урон от стихии огня,<br />равный </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базового физического урона питомца.</span>";
    break;
    case "7491" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ледяной снаряд&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>8</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Стреляет в противника осколком льда, нанося урон от стихии воды,<br />равный </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базового физического урона питомца.</span>";
    break;
    case "7501" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ядовитый туман&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>8</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Окутывает противника едким туманом, который наносит урон от стихии дерева,<br />равный </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базового физического урона питомца.</span>";
    break;
    case "7511" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Разряд молнии&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>8</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Призывает молнию, которая наносит противнику урон от стихии металла,<br />равный </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базового физического урона питомца.</span>";
    break;
    case "7521" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Песчаный шквал&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /><br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>8</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Порыв песчаной бури, наносящий противнику урон от земли,<br />равный </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базового физического урона питомца.</span>";
    break;
    case "7531" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Призывный рык&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5</span><span style='color:#ffcb4a'><br /><br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>15</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Издавая громовой рык, питомец провоцирует одного из противников атаковать его.</span>";
    break;
    case "7541" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Жуткий вой&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /><br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Пугает врага жутким воем, снижая его магическую защиту на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> на 15 сек.</span>";
    break;
    case "7551" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Слабина&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Выявляет слабое место в доспехах противника, снижая его физическую защиту на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> на 15 сек.</span>";
    break;
    case "7561" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Устрашение&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Уменьшает урон, наносимый противником, на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> на 15 сек.</span>";
    break;
    case "7571" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Пронзительный крик&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /><br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Питомец издает резкий вопль и с вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> прерывает подготовку заклинания противника.</span>";
    break;
    case "7581" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Замедление&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>На 6 секунд снижает скорость передвижения противника на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>.</span>";
    break;
    case "7591" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Прочная шкура&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>60</span><span style='color:#ffcb4a'> сек.<br /><br />\r</span><span style='color:#ffffff'>Уменьшает получаемый урон на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> в течение 15 сек.</span>";
    break;
    case "7601" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Прилив сил&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>3 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br />\r</span><span style='color:#ffffff'>Восстанавливает </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> максимального запаса здоровья.</span>";
    break;
    case "7611" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Наскок&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>2 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>60</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Внезапная атака, которая с вероятностью 80% оглушает противника на 3 сек.<br />Если противника удалось оглушить, скорость атаки повышается на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> на 15 сек.</span>";
    break;
    case "7951" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Похищение жизни&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>3 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Питомец поглощает ЖС противника в размере </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'><br />своего максимального запаса ЖС, восстанавливая себе здоровье.</span>";
    break;
    case "7961" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Похищение энергии&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>3 </span><span style='color:#ffcb4a'> <br /><br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Питомец&nbsp;&nbsp;поглощает МЭ противника в размере </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'><br />своего максимального запаса ЖС и преобразует ее в свое здоровье.</span>";
    break;
    case "7971" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Осушение жизни<br /><br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Предварительный навык:&nbsp;&nbsp;</span><span style='color:#ffffff'>Похищение жизни (уровень 3)<br /><br /></span><span style='color:#ffffff'>Питомец поглощает ЖС противника в размере половины<br />своего максимального запаса ЖС, восстанавливая себе здоровье.</span>";
    break;
    case "7981" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Осушение энергии<br /><br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Предварительный навык&nbsp;&nbsp;</span><span style='color:#ffffff'>Похищение энергии (уровень 3)<br /><br /></span><span style='color:#ffffff'>Питомец поглощает МЭ противника в размере половины<br />своего максимального запаса ЖС и преобразует ее в свое здоровье.</span>";
    break;
    case "7991" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Жертва<br /><br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Теряя 75% текущего запаса здоровья питомец наносит урон, равный 400% базового физического урона.</span>";
    break;
    case "8001" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Неотвратимый удар&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Точный удар, наносящий противнику </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> ед. урона вне зависимости от уровня защиты.</span>";
    break;
    case "8011" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Отражение&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>3</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Наносит атакующим в ближнем бою </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> наносимого ими урона.<br />Время действия - 1 ч.</span>";
    break;
    case "8021" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Острые когти&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур. </span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'>ур. <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>3 </span><span style='color:#ffcb4a'>сек.<br /></span><span style='color:#ffffff'>Увеличивает базовый физический урон питомца на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> на 1 ч.</span>";
    break;
    case "8031" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Сила духа&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>3</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Увеличивает магическую защиту на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> на 1 ч.</span>";
    break;
    case "8041" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Толстая шкура&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>3</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Повышает физическую защиту на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> на 1 ч.</span>";
    break;
    case "8051" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Удача&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Уровень "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Макс. ур.&nbsp;&nbsp;</span><span style='color:#ffffff'>5 </span><span style='color:#ffcb4a'> <br /></span><span style='color:#ffcb4a'>Перезарядка:　</span><span style='color:#ffffff'>3</span><span style='color:#ffcb4a'> сек.<br /><br /></span><span style='color:#ffffff'>Повышает максимальный запас здоровья на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> на 1 ч.</span>";
    break;
    case "20581" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Дух битв&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Получаемый от игроков урон снижается на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>.</span>";
    break;
    case "20591" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Тяжелый удар&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> оглушает цель на </span><span style='color:#96f5ff'>2</span><span style='color:#ffffff'> сек.</span>";
    break;
    case "20611" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Укрытие духа&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>В течение </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> сек. враг не может выбрать вашего питомца.</span>";
    break;
    case "20621" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Кровожадность&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> восстанавливает </span><span style='color:#96f5ff'>"+pet[skill_tableau][4][lvl]+"%</span><span style='color:#ffffff'> макс. здоровья.</span>";
    break;
    case "20771" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Священная особа<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Получаемый персонажем прямой урон снижается на 60%,<br />макс. здоровье увеличивается на 30%.<br /><br /></span><span style='color:#a6caf0'>Специальное умение небесного старца.</span>";
    break;
    case "20781" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>На крыльях феникса<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>1.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Цели наносится огненный урон в размере 133% от силы атаки,<br />целям в воздухе наносится тройной урон.<br /><br /></span><span style='color:#a6caf0'>Специальное умение великого феникса.</span>";
    break;
    case "20791" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Бог в латах<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>1.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>15</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Врагам по прямой на расстоянии 10 м наносится физ. урон в размере 100% силы атаки.<br />Уменьшает получаемый персонажем урон на 15%, действие: 15 сек.<br /><br /></span><span style='color:#a6caf0'>Снижение урона может складываться с эффектом прочной шкуры<br /><br /></span><span style='color:#a6caf0'>Специальное умение великого духа.</span>";
    break;
    case "20801" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Костяной серп<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>15</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Цели наносится физ. урон в размере 200% от силы атаки,<br />монстрам наносится дополнительный физ. урон в размере 150% от силы атаки.<br /><br /></span><span style='color:#a6caf0'>Специальное умение призрака правителя.</span>";
    break;
    case "20811" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ледяной панцирь<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Уровень защиты увеличивается на 20 ед.<br /><br /></span><span style='color:#a6caf0'>Специальное умение странника.</span>";
    break;
    case "20821" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Жало<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>20</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Цели наносится урон стихией дерева в размере 100% от силы атаки, скорость полета снижается на 50%<br />на 8 сек., целям в воздухе наносится тройной урон.<br /><br /></span><span style='color:#a6caf0'>Специальное умение жалящей пчелы.</span>";
    break;
    case "20831" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Огненная купель<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>90</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Восстанавливает 70% здоровья, на 6 сек. защита увеличивается на 200 ед.<br /><br /></span><span style='color:#a6caf0'>Специальное умение кристалла кармы.</span>";
    break;
    case "20841" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Быстрая стрельба<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>20</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Скорость атаки увеличивается на 100% на 8 сек.<br /><br /></span><span style='color:#a6caf0'>Специальное умение шипа разлуки.</span>";
    break;
    case "20851" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Цунами<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>15</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Цели наносится урон от воды в размере 650% от силы атаки.<br /><br /></span><span style='color:#a6caf0'>Специальное умение священного карпа иллюзий.</span>";
    break;
    case "20861" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Покров ночи<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>20</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>В течение </span><span style='color:#96f5ff'>"+pet[skill_tableau][2][lvl]+"</span><span style='color:#ffffff'> сек. вас нельзя выбрать.<br /><br /></span><span style='color:#a6caf0'>Специальное умение крадущегося в ночи.</span>";
    break;
    case "20871" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Воздушный штурм<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>15</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Отбрасывает цель на 10 м, действует на игроков.<br /><br /></span><span style='color:#a6caf0'>Специальное умение белого поросенка.</span>";
    break;
    case "20881" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ду-ду<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью 70% оглушает цель на 2 сек.<br /><br /></span><span style='color:#a6caf0'>Специальное умение медведя-трубача.</span>";
    break;
    case "20891" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Верный пес<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>В течение 4 сек. вражеский игрок может выбрать только Рекса.<br /><br />'Беги, хозяин!'<br /><br /></span><span style='color:#a6caf0'>Специальное умение Рекса.</span>";
    break;
    case "20901" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Бег пламени<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>На 10 сек. скорость ягуара возрастает до предела, уклонение увеличивается на 400%.<br /><br />'Не убежишь!'<br /><br /></span><span style='color:#a6caf0'>Специальное умение ягуара.</span>";
    break;
    case "20911" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Сонливость<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Снижает скорость атаки, передвижения и<br />активации на 50% на 8 сек.<br /><br /></span><span style='color:#a6caf0'>Специальное умение лунной жабы.</span>";
    break;
    case "20921" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Токсин слабости<br /><br /></span><span style='color:#ffcb4a'>Дальность&nbsp;&nbsp;</span><span style='color:#ffffff'>12 м<br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Снижает физ. и маг. атаку всех врагов в радиусе 10 м на 50% на 4 сек. Если цель - игрок, то эффект достигает 200%.<br /><br /></span><span style='color:#a6caf0'>Специальное умение рунного скорпиона.</span>";
    break;
    case "20931" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Крушитель<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Умения наносят монстрам на 30% больше урона,<br />макс. здоровье увеличивается на 30%.<br /><br /></span><span style='color:#a6caf0'>Увеличение урона может складываться с эффектом 'Потрошитель'.<br /><br /></span><span style='color:#a6caf0'>Специальное умение гарпии.</span>";
    break;
    case "20941" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Узник&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> парализует цель на </span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'> сек.</span>";
    break;
    case "20961" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Утомление&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> замедляет цель на </span><span style='color:#96f5ff'>70%</span><span style='color:#ffffff'> на </span><span style='color:#96f5ff'>6</span><span style='color:#ffffff'> сек.</span>";
    break;
    case "20981" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Тишина&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> запечатывает цель на </span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'> сек.</span>";
    break;
    case "21001" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Сломанный клинок&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> выбивает из рук врага оружие на </span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'> сек.</span>";
    break;
    case "21021" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Перегруз&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'><br />увеличивает интервалы между атаками врага на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> на </span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'> сек.<br />На монстров действует слабее.</span>";
    break;
    case "21041" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Шум&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>После запуска умения есть вероятность </span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'><br />увеличить время активации у цели на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> на </span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'> сек., для<br />монстров эффект снижен.</span>";
    break;
    case "21061" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Сглаз&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> прерывает колдовство врага. На монстров действует слабее.</span>";
    break;
    case "21081" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Поглощение души&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'> уменьшает ци врага на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> ед.</span>";
    break;
    case "21101" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Острие&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> наносит цели урон стихией металла, равный показателю атаки.<br />На монстров действует слабее.</span>";
    break;
    case "21121" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Запрет полетов&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> лишает цель возможности летать на </span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'> сек.</span>";
    break;
    case "21141" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Порча&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'> может ослабить физическую и магическую атаку врага на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'><br />на </span><span style='color:#96f5ff'>6</span><span style='color:#ffffff'> сек. На монстров действует менее эффективно.</span>";
    break;
    case "21161" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Провокация&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'> позволяет разозлить врага.<br />Чем выше уровень умения, тем эффективнее оно действует.</span>";
    break;
    case "21181" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Азарт&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> повышает скорость атаки на </span><span style='color:#96f5ff'>25%</span><span style='color:#ffffff'> на </span><span style='color:#96f5ff'>12</span><span style='color:#ffffff'> сек.</span>";
    break;
    case "21201" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Точность&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Меткость увеличивается на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>.</span>";
    break;
    case "21211" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Потрошитель&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>10</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Умения наносят монстрам на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> больше урона.</span>";
    break;
    case "21221" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Подвижность&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> персонаж уклоняется от обычного урона.</span>";
    break;
    case "21231" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Регенерация&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Каждые </span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'> сек. восстанавливается </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> максимального здоровья,<br />действие: </span><span style='color:#96f5ff'>30</span><span style='color:#ffffff'> сек.</span>";
    break;
    case "21241" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Непоколебимость&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Уровень защиты увеличивается на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> ед.</span>";
    break;
    case "21251" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Боевой задор&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Уровень атаки увеличивается на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> ед.</span>";
    break;
    case "21261" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Бог войны&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Уровень атаки и защиты увеличивается на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> ед.</span>";
    break;
    case "21271" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Энергия духа&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Уровень атаки и защиты увеличивается на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> ед., урон от действий других игроков <br />уменьшается на </span><span style='color:#96f5ff'>55%</span><span style='color:#ffffff'>.</span>";
    break;
    case "21281" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Прорыв&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Иммунитет к ограничениям скорости.</span>";
    break;
    case "21291" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Самолечение&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>90</span><span style='color:#ffcb4a'> сек.<br />Восстанавливается </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> максимального здоровья.</span>";
    break;
    case "21301" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Кулак огня&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.2</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>1.0</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>1.0</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Наносит урон огнем в размере </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базовой силы атаки питомца.</span>";
    break;
    case "21311" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Решимость&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Наносит физический урон в размере </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базовой силы атаки питомца.</span>";
    break;
    case "21321" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Удар из-за угла&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Дальность　</span><span style='color:#ffffff'>27 м<br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>5</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Наносит физический урон в размере </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базовой силы атаки питомца.</span>";
    break;
    case "21331" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Финал&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Наносит физический урон в размере </span><span style='color:#96f5ff'>100%</span><span style='color:#ffffff'>-</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базовой силы атаки питомца.<br />Чем ниже уровень здоровья цели, тем больше урон.<br />На монстров действует слабее.</span>";
    break;
    case "21341" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Внезапный гром&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.8</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Наносит физический урон в размере </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> базовой силы атаки питомца.<br />Цели в воздухе получают </span><span style='color:#96f5ff'>трехкратные</span><span style='color:#ffffff'> повреждения.</span>";
    break;
    case "21351" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Рев&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.4</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.6</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>20</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>В радиусе </span><span style='color:#96f5ff'>12</span><span style='color:#ffffff'> м вокруг цели наносит врагам физический урон в размере </span><span style='color:#96f5ff'>100%</span><span style='color:#ffffff'> от силы атаки питомца.<br />В зависимости от уровня умения и максимального здоровья питомца может разозлить врага.</span>";
    break;
    case "21361" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Экзорцизм&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Питомец наносит монстрам на </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'> ед. урона больше.</span>";
    break;
    case "21381" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Полный разгром<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.2</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: 　</span><span style='color:#ffffff'>2.5</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>15</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Наносит цели физ. урон в размере </span><span style='color:#96f5ff'>300%</span><span style='color:#ffffff'> от силы атаки питомца<br />и парализует ее на </span><span style='color:#96f5ff'>2</span><span style='color:#ffffff'> сек.<br />Показатель атаки персонажа увеличивается на </span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'>.<br /><br /></span><span style='color:#a6caf0'>После забывания это умение выучить нельзя.</span>";
    break;
    case "21391" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Тяжелое бремя<br /><br /></span><span style='color:#ffcb4a'>Дальность　</span><span style='color:#ffffff'>15 м<br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.2</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: 　</span><span style='color:#ffffff'>1.3</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Наносит цели и врагам в радиусе </span><span style='color:#96f5ff'>6</span><span style='color:#ffffff'> м физ. урон в размере </span><span style='color:#96f5ff'>100%</span><span style='color:#ffffff'> от силы атаки питомца.<br />Оглушает вражеских игроков на </span><span style='color:#96f5ff'>2</span><span style='color:#ffffff'> сек.<br /><br /></span><span style='color:#a6caf0'>После забывания это умение выучить нельзя.</span>";
    break;
    case "21401" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ледяная грань<br /><br /></span><span style='color:#ffcb4a'>Дальность　</span><span style='color:#ffffff'>27 м<br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.5</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: 　</span><span style='color:#ffffff'>1.0</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>1.0</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Наносит урон стихией воды в размере </span><span style='color:#96f5ff'>200%</span><span style='color:#ffffff'> от силы атаки питомца,<br />монстрам - в размере </span><span style='color:#96f5ff'>350%</span><span style='color:#ffffff'>.<br /><br /></span><span style='color:#a6caf0'>Отлично работает против вражеских питомцев.<br /></span><span style='color:#a6caf0'>После забывания это умение выучить нельзя.</span>";
    break;
    case "21411" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Листопад<br /><br /></span><span style='color:#ffcb4a'>Дальность　</span><span style='color:#ffffff'>27 м<br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>1.0</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: 　</span><span style='color:#ffffff'>1.5</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>15</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Наносит цели и врагам в радиусе </span><span style='color:#96f5ff'>10</span><span style='color:#ffffff'> м урон стихией дерева в размере </span><span style='color:#96f5ff'>200%</span><span style='color:#ffffff'> от силы атаки питомца,<br />монстрам - в размере </span><span style='color:#96f5ff'>300%</span><span style='color:#ffffff'>.<br /><br /></span><span style='color:#a6caf0'>Отлично работает против вражеских питомцев.<br /></span><span style='color:#a6caf0'>После забывания это умение выучить нельзя.</span>";
    break;
    case "21421" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ломающий горы<br /><br /></span><span style='color:#ffcb4a'>Дальность　</span><span style='color:#ffffff'>27 м<br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>1.0</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: 　</span><span style='color:#ffffff'>1.5</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>Наносит цели и врагам в радиусе </span><span style='color:#96f5ff'>10</span><span style='color:#ffffff'> м физ. урон в размере </span><span style='color:#96f5ff'>200%</span><span style='color:#ffffff'> от силы атаки питомца,<br />а монстров оглушает на </span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'> сек.<br /><br /></span><span style='color:#a6caf0'>После забывания это умение выучить нельзя.</span>";
    break;
    case "21461" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Тень демона&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ур.: "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Подготовка: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Запуск: </span><span style='color:#ffffff'>0.1</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffcb4a'>Интервал: </span><span style='color:#ffffff'>30</span><span style='color:#ffcb4a'> сек.<br /></span><span style='color:#ffffff'>С вероятностью </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'> персонаж уклоняется от негативных эффектов.</span>";
    break;
  }
}
