function affiche(){
  skill_tableau = document.forms['skill'].nomskill.value;

  if ( level > pet_level[skill_tableau] )
  {
    lvl = pet_level[skill_tableau];
  }
  else
  {
    lvl = level;
  }

  //lvl pet + sp requis
  document.getElementById('petlvl').innerHTML="<span style=\"color:#96f5ff\">"+pet[skill_tableau][0][lvl]+"</span>";
  document.getElementById('spirit').innerHTML="<span style=\"color:#96f5ff\">"+pet[skill_tableau][1][lvl]+"</span>";

  //info skill
  switch (skill_tableau) {
    case "6871" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Raging Attack&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>8&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>A powerful attack that deals damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>of base attack.</span>";
    break;
    case "7471" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Raging Bite&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>15&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>A rending bite that causes bleeding for 9 sec. <br />Total bleed damage is equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>of the base attack.</span>";
    break;
    case "7481" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Fireball&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>8&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Hurls a fireball at an enemy dealing fire damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>of base attack.</span>";
    break;
    case "7491" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Ice Shard&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>8&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Shoots an Ice Shard dealing water damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>of base attack.</span>";
    break;
    case "7501" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Poison Mist&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>8&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Deadly poison gas that deals wood damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>of base attack.</span>";
    break;
    case "7511" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Call Lightning&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>8&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Summons a bolt of lightning that deals Metal damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>of basic attack.</span>";
    break;
    case "7521" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Rising Sand&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>8&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Throws sand at an enemy dealing earth damage equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>of base attack.</span>";
    break;
    case "7531" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Tiger’s Challenge&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>15&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /></span><span style='color:#ffffff'>Provokes enemies within range with a thunderous roar.</span>";
    break;
    case "7541" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Wailing Cry&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>30&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Frightens enemies with an eerie howl. For the next 15 sec. their MDef is reduced </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>.</span>";
    break;
    case "7551" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Shatter&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>30&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Lowers enemy defense by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>for 15 sec.</span>";
    break;
    case "7561" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Injure&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>30&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Frightens enemies reducing their defense by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>for 15 sec.</span>";
    break;
    case "7571" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Piercing Cry&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>10&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /></span><span style='color:#ffffff'>A Piercing Cry, that has a </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>chance of interrupting enemy spells.</span>";
    break;
    case "7581" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Slow&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>10&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /></span><span style='color:#ffffff'>Target is slowed for 6 sec. Movement is reduced by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>.</span>";
    break;
    case "7591" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Tough Hide&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>60&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br />\r</span><span style='color:#ffffff'>Reduces damage suffered by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>for 15 sec.</span>";
    break;
    case "7601" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Inspire&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>3&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>10&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br />\r</span><span style='color:#ffffff'>Recovers </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>of maximum health.</span>";
    break;
    case "7611" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Snipsnap&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>2&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>60&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>80% to paralyze opponents for 3sec., if successful within 15sec. aspd increase by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>.</span>";
    break;
    case "7951" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Drain Life&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>3&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>30&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Absorbs HP equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>of caster's Max HP.</span>";
    break;
    case "7961" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Drain Mana&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>3&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>30&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Drains enemy mana equal to </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>and converts it to health.</span>";
    break;
    case "7971" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Draw Life<br /><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>30&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /></span><span style='color:#ffcb4a'>Prerequisite Skill:&nbsp;&nbsp;</span><span style='color:#ffffff'>Drain Life Lv. 3<br /><br /></span><span style='color:#ffffff'>Drains health equal to half the user's max health.</span>";
    break;
    case "7981" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Draw Mana<br /><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>30&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /></span><span style='color:#ffcb4a'>Prerequisite Skill&nbsp;&nbsp;</span><span style='color:#ffffff'>Drain Mana Lv. 3<br /><br /></span><span style='color:#ffffff'>Drains mana from enemy equal to half the users max health. Converts drained mana to health.</span>";
    break;
    case "7991" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Sacrifice<br /><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>30&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Burns 75% of current health to deal massive damage equal to 400% of base attack.</span>";
    break;
    case "8001" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Smash&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>30&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Fierce attack that deals </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+" </span><span style='color:#ffffff'>damage, ignoring Def.</span>";
    break;
    case "8011" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Retribution&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>3&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /><br /></span><span style='color:#ffffff'>Reflects </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>of physical attacks received for 1 hr.</span>";
    break;
    case "8021" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Potence&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>3&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /></span><span style='color:#ffffff'>Increases attack by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>for 1 hour.</span>";
    break;
    case "8031" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Driving Spirit&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>3&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br />\r</span><span style='color:#ffffff'>Increases magical defense by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>for 1 hour.</span>";
    break;
    case "8041" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Iron Armor&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>3&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br /></span><span style='color:#ffffff'>Defense is increased by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>for 1 hr.</span>";
    break;
    case "8051" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>Fortitude&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lv. "+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>Max Lv.&nbsp;&nbsp;</span><span style='color:#ffffff'>5&nbsp;&nbsp;</span><span style='color:#ffcb4a'><br /></span><span style='color:#ffcb4a'>Cooldown:&nbsp;&nbsp;</span><span style='color:#ffffff'>3&nbsp;&nbsp;</span><span style='color:#ffcb4a'>sec.<br />\r</span><span style='color:#ffffff'>Maximum health is increased by </span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"% </span><span style='color:#ffffff'>for 1 hour.</span>";
    break;
    case "20581" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>战魂　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>受到来自于玩家的直接伤害减少</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>。</span>";
    break;
    case "20591" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>重击　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的概率<br />使其昏迷</span><span style='color:#96f5ff'>2</span><span style='color:#ffffff'>秒。</span>";
    break;
    case "20611" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>神隐　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>使自身无法被玩家选中，持续</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>秒。</span>";
    break;
    case "20621" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>嗜血　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的概率<br />恢复自身</span><span style='color:#96f5ff'>"+pet[skill_tableau][4][lvl]+"%</span><span style='color:#ffffff'>的最大生命值。</span>";
    break;
    case "20771" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>斗战圣体<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>受到来自于玩家的直接伤害减少60%，<br />生命上限提高30%。<br /><br /></span><span style='color:#a6caf0'>齐天大圣专属技能</span>";
    break;
    case "20781" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>凤翼天翔<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>1.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成133%攻击力的火焰伤害，<br />对空中目标造成3倍伤害。<br /><br /></span><span style='color:#a6caf0'>明尊凤凰专属技能</span>";
    break;
    case "20791" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>金甲天神<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>1.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对前方直线上10米内的敌人造成100%攻击力的高仇恨物理伤害，<br />且自身获得伤害减免15%的效果，持续15秒。<br /><br /></span><span style='color:#a6caf0'>减伤效果这可以和硬皮叠加<br /><br /></span><span style='color:#a6caf0'>巨灵神专属技能</span>";
    break;
    case "20801" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>骨镰<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成200%攻击力的单体物理伤害，<br />对怪物额外造成150%攻击力的物理伤害。<br /><br /></span><span style='color:#a6caf0'>对敌方宠物造成海量伤害<br /></span><span style='color:#a6caf0'>皇骸专属技能</span>";
    break;
    case "20811" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>冰石铠甲<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>防御等级提高20点。<br /><br /></span><span style='color:#a6caf0'>巅峰行者专属技能</span>";
    break;
    case "20821" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>蜂刺<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>20　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成100%攻击力的木系伤害且降低其飞行速度50%，<br />持续8秒，对空中目标造成3倍伤害。<br /><br /></span><span style='color:#a6caf0'>刺棘蜂专属技能</span>";
    break;
    case "20831" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>浴火重生<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>90　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>恢复70%的生命值,且在6秒内防御等级增加200。<br /><br /></span><span style='color:#a6caf0'>业火结晶专属技能</span>";
    break;
    case "20841" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>急速射击<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>20　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>自身攻速提高100%，持续8秒。<br /><br /></span><span style='color:#a6caf0'>仙幻离别刺专属技能</span>";
    break;
    case "20851" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>海啸<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成650%攻击力的水系伤害。<br /><br /></span><span style='color:#a6caf0'>幻境神仙鱼专属技能</span>";
    break;
    case "20861" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>夜幕<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>20　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>使自身无法被玩家选中，持续</span><span style='color:#96f5ff'>"+pet[skill_tableau][2][lvl]+"</span><span style='color:#ffffff'>秒。<br /><br /></span><span style='color:#a6caf0'>永夜徘徊者专属技能</span>";
    break;
    case "20871" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>飞天蕾丝突击<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>将目标击退10米，对玩家有效。<br /><br /></span><span style='color:#a6caf0'>豚小白专属技能</span>";
    break;
    case "20881" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>嘟<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>70%概率击晕目标2秒。<br /><br /></span><span style='color:#a6caf0'>嘟嘟熊王专属技能</span>";
    break;
    case "20891" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>忠犬<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>使敌方玩家在4秒内只能选中忠良公。<br /><br />“主人，快跑！”<br /><br /></span><span style='color:#a6caf0'>忠良公专属技能</span>";
    break;
    case "20901" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>暗影冲刺<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>四条腿的崔斯特跑的更快了！10秒内移动速度提高至极限，且闪避提高400%。<br /><br />“把我的身体还给我！”你似乎能听到这样的呼喊，别在意，那只是错觉。<br /><br /></span><span style='color:#a6caf0'>崔斯特专属技能</span>";
    break;
    case "20911" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>残废术<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>使目标的攻击速度、移动速度及<br />吟唱速度减少50%，持续8秒。<br /><br /></span><span style='color:#a6caf0'>月宫蟾专属技能</span>";
    break;
    case "20921" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>虚弱毒素<br /><br /></span><span style='color:#ffcb4a'>施放距离　</span><span style='color:#ffffff'>12米<br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>使目标周围10米内的所有敌人物理攻击力法术攻击力降低50%，持续4秒，目标为玩家时效果提高到200%。<br /><br /></span><span style='color:#a6caf0'>魔纹蝎专属技能</span>";
    break;
    case "20931" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>灵毁<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>使自身对怪物造成的直接技能伤害增加30%，<br />生命上限提高30%。<br /><br /></span><span style='color:#a6caf0'>伤害增加效果可以和屠魔叠加<br /><br /></span><span style='color:#a6caf0'>九天鲲鹏专属技能</span>";
    break;
    case "20941" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>禁锢　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的<br />概率使其定身</span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'>秒。</span>";
    break;
    case "20961" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>致残　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的<br />概率使其减速</span><span style='color:#96f5ff'>70%</span><span style='color:#ffffff'>，持续</span><span style='color:#96f5ff'>6</span><span style='color:#ffffff'>秒。</span>";
    break;
    case "20981" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>沉寂　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的<br />概率使其封印</span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'>秒。</span>";
    break;
    case "21001" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>破刃　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的<br />概率使其武器失效</span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'>秒。</span>";
    break;
    case "21021" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>超重　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'>的<br />概率使目标攻击间隔延长</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>，持续</span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'>秒，对怪<br />物效果较低。</span>";
    break;
    case "21041" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>噪音　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'>的<br />概率使目标吟唱时间延长</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>，持续</span><span style='color:#96f5ff'>4</span><span style='color:#ffffff'>秒，对怪<br />效果较低。</span>";
    break;
    case "21061" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>魔音　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的<br />概率打断目标施法，对怪物效果较低。</span>";
    break;
    case "21081" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>摄魂　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'>的<br />概率减少目标</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>点元气。</span>";
    break;
    case "21101" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>锋锐　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的<br />概率对目标造成相当于自身基础攻击力的金系<br />伤害，对怪物效果较低。</span>";
    break;
    case "21121" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>禁空　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的<br />概率对目标禁止飞行</span><span style='color:#96f5ff'>10</span><span style='color:#ffffff'>秒。</span>";
    break;
    case "21141" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>侵蚀　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'>的<br />概率降低目标</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的物理攻击力和法术攻击力，<br />持续</span><span style='color:#96f5ff'>6</span><span style='color:#ffffff'>秒，对怪物效果较低。</span>";
    break;
    case "21161" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>挑衅　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'>的<br />概率对目标造成大量仇恨，技能等级越高仇恨<br />量越高。</span>";
    break;
    case "21181" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>狂热　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>开启该技能后，对目标进行普通攻击时有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的<br />概率使自身攻击速度提高</span><span style='color:#96f5ff'>25%</span><span style='color:#ffffff'>，持续</span><span style='color:#96f5ff'>12</span><span style='color:#ffffff'>秒。</span>";
    break;
    case "21201" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>精准　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>命中提高</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>。</span>";
    break;
    case "21211" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>屠魔　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>使自身对怪物造成的直接技能伤害增加</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>。</span>";
    break;
    case "21221" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>闪灵　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>使自身有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的概率闪避常规伤害。</span>";
    break;
    case "21231" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>再生　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>每</span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'>秒恢复自身</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的最大生命值，<br />持续</span><span style='color:#96f5ff'>30</span><span style='color:#ffffff'>秒。</span>";
    break;
    case "21241" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>不屈　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>防御等级增加</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>点。</span>";
    break;
    case "21251" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>斗志　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>攻击等级增加</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>点。</span>";
    break;
    case "21261" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>战神　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>攻击防御等级增加</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>点。</span>";
    break;
    case "21271" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>神魂　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>攻击防御等级增加</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>点，受到来自于玩家的直接伤害<br />减少</span><span style='color:#96f5ff'>55%</span><span style='color:#ffffff'>。</span>";
    break;
    case "21281" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>霸体　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>免疫移动限制。</span>";
    break;
    case "21291" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>自愈　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>90　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>恢复自身</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的最大生命值。</span>";
    break;
    case "21301" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>火拳　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.2&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>1.0&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>1.0　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成相当于自身</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>基础攻击力的火系伤害。</span>";
    break;
    case "21311" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>裁决　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成相当于自身</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>基础攻击力的物理伤害。</span>";
    break;
    case "21321" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>狙击　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>施放距离　</span><span style='color:#ffffff'>27米<br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>5　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成相当于自身</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>基础攻击力的物理伤害。</span>";
    break;
    case "21331" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>终结　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成相当于自身</span><span style='color:#96f5ff'>100%</span><span style='color:#ffffff'>至</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>基础攻击力<br />的物理伤害，目标生命百分比越低伤害越高，<br />对怪物效果较低。</span>";
    break;
    case "21341" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>破空　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.8&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成相当于自身</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>基础攻击力的物理<br />伤害，对空中目标造成</span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'>倍伤害。</span>";
    break;
    case "21351" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>怒吼　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.4&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.6&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>20　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对自身周围</span><span style='color:#96f5ff'>12</span><span style='color:#ffffff'>米内的敌人造成</span><span style='color:#96f5ff'>100%</span><span style='color:#ffffff'>攻击力的物理<br />伤害，造成海量仇恨。仇恨量与技能等级与宠物<br />最大生命值有关。</span>";
    break;
    case "21361" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>猎魔　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1 </span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>10　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>猎魔等级增加</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"</span><span style='color:#ffffff'>点。</span>";
    break;
    case "21381" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>横扫六合<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.2&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>2.5&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>15　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成</span><span style='color:#96f5ff'>300%</span><span style='color:#ffffff'>攻击力的物理伤害，<br />将其定身</span><span style='color:#96f5ff'>2</span><span style='color:#ffffff'>秒，且自身攻击力提高</span><span style='color:#96f5ff'>30%</span><span style='color:#ffffff'>。<br /><br /></span><span style='color:#a6caf0'>该技能遗忘后无法再次学习</span>";
    break;
    case "21391" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>千斤压顶<br /><br /></span><span style='color:#ffcb4a'>施放距离　</span><span style='color:#ffffff'>15米<br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.2&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>1.3&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标及周围</span><span style='color:#96f5ff'>6</span><span style='color:#ffffff'>米范围内的敌人造成相当于<br />自身</span><span style='color:#96f5ff'>100%</span><span style='color:#ffffff'>基础攻击力的物理伤害，对玩家造<br />成</span><span style='color:#96f5ff'>2</span><span style='color:#ffffff'>秒昏迷。<br /><br /></span><span style='color:#a6caf0'>该技能遗忘后无法再次学习</span>";
    break;
    case "21401" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>冰棱<br /><br /></span><span style='color:#ffcb4a'>施放距离　</span><span style='color:#ffffff'>27米<br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.5&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>1.0&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>1.0　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标造成相当于自身</span><span style='color:#96f5ff'>200%</span><span style='color:#ffffff'>基础攻击力的水系<br />伤害,对怪物额外造成</span><span style='color:#96f5ff'>150%</span><span style='color:#ffffff'>攻击力的水系伤害。<br /><br /></span><span style='color:#a6caf0'>对敌方宠物造成海量伤害<br /></span><span style='color:#a6caf0'>该技能遗忘后无法再次学习</span>";
    break;
    case "21411" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>落叶飞花<br /><br /></span><span style='color:#ffcb4a'>施放距离　</span><span style='color:#ffffff'>27米<br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>1.0&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>1.5&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>1.5&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标及周围</span><span style='color:#96f5ff'>10</span><span style='color:#ffffff'>米范围内的敌人造成相当于自身<br /></span><span style='color:#96f5ff'>200%</span><span style='color:#ffffff'>基础攻击力的木系伤害,对怪物额外造成</span><span style='color:#96f5ff'>100%<br /></span><span style='color:#ffffff'>攻击力的木系伤害。<br /><br /></span><span style='color:#a6caf0'>对敌方宠物造成海量伤害<br /></span><span style='color:#a6caf0'>该技能遗忘后无法再次学习</span>";
    break;
    case "21421" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>五指断岳<br /><br /></span><span style='color:#ffcb4a'>施放距离　</span><span style='color:#ffffff'>27米<br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>1.0&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>1.5&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>对目标及周围</span><span style='color:#96f5ff'>10</span><span style='color:#ffffff'>米范围内的敌人造成相当于自身<br /></span><span style='color:#96f5ff'>200%</span><span style='color:#ffffff'>基础攻击力的物理伤害，对怪物造成</span><span style='color:#96f5ff'>3</span><span style='color:#ffffff'>秒昏迷。<br /><br /></span><span style='color:#a6caf0'>该技能遗忘后无法再次学习</span>";
    break;
    case "21461" :
      document.getElementById('texte').innerHTML="<span style='color:#ffffff'>魅影　　　　　　　　　　　　　等级"+pet[skill_tableau][2][lvl]+"<br /><br /></span><span style='color:#ffcb4a'>准备时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放时间　</span><span style='color:#ffffff'>0.1&nbsp;&nbsp;</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffcb4a'>施放间隔　</span><span style='color:#ffffff'>30　</span><span style='color:#ffcb4a'>秒<br /></span><span style='color:#ffffff'>使自身有</span><span style='color:#96f5ff'>"+pet[skill_tableau][3][lvl]+"%</span><span style='color:#ffffff'>的概率闪避负面状态。</span>";
    break;
  }
}
